export const humanAssets = [
  { id: 'idle', zhName: '正面待机', direction: 'front', category: 'baseline', source: 'v1', action: 'neutral standing pose' },
  { id: 'point-right', zhName: '指向右侧', direction: 'right', category: 'directional', source: 'v1', action: 'pointing clearly to the right' },
  { id: 'think', zhName: '正面思考', direction: 'front', category: 'reasoning', source: 'v1', action: 'thinking with one hand at the chin' },
  { id: 'approve', zhName: '正面认可', direction: 'front', category: 'decision', source: 'v1', action: 'approving with a thumbs-up' },
  { id: 'operate', zhName: '正面操作', direction: 'front', category: 'execution', source: 'v1', action: 'operating an imaginary interface with both hands' },
  { id: 'surprised', zhName: '正面惊讶', direction: 'front', category: 'reaction', source: 'v1', action: 'surprised with raised hands' },
  { id: 'point-left', zhName: '指向左侧', direction: 'left', category: 'directional', source: 'generated', action: 'pointing clearly to the left with one extended index finger' },
  { id: 'present-right', zhName: '展示右侧', direction: 'right', category: 'directional', source: 'generated', action: 'open-palm presentation gesture toward content on the right' },
  { id: 'present-left', zhName: '展示左侧', direction: 'left', category: 'directional', source: 'generated', action: 'open-palm presentation gesture toward content on the left' },
  { id: 'look-right', zhName: '观察右侧', direction: 'right', category: 'directional', source: 'generated', action: 'turning head and upper body to inspect content on the right' },
  { id: 'look-left', zhName: '观察左侧', direction: 'left', category: 'directional', source: 'generated', action: 'turning head and upper body to inspect content on the left' },
  { id: 'handoff-right', zhName: '向右交付', direction: 'right', category: 'directional', source: 'generated', action: 'offering an imaginary task or artifact toward the right with both hands, without holding an object' },
  { id: 'handoff-left', zhName: '向左交付', direction: 'left', category: 'directional', source: 'generated', action: 'offering an imaginary task or artifact toward the left with both hands, without holding an object' },
  { id: 'receive-right', zhName: '从右接收', direction: 'right', category: 'directional', source: 'generated', action: 'receiving an imaginary item from the right with open hands, without holding an object' },
  { id: 'receive-left', zhName: '从左接收', direction: 'left', category: 'directional', source: 'generated', action: 'receiving an imaginary item from the left with open hands, without holding an object' },
  { id: 'operate-right', zhName: '操作右侧', direction: 'right', category: 'directional', source: 'generated', action: 'operating an imaginary interface positioned on the right' },
  { id: 'operate-left', zhName: '操作左侧', direction: 'left', category: 'directional', source: 'generated', action: 'operating an imaginary interface positioned on the left' },
  { id: 'walk-right', zhName: '向右推进', direction: 'right', category: 'directional', source: 'generated', action: 'walking or advancing purposefully toward the right' },
  { id: 'walk-left', zhName: '向左推进', direction: 'left', category: 'directional', source: 'generated', action: 'walking or advancing purposefully toward the left' },
  { id: 'explain-front', zhName: '正面讲解', direction: 'front', category: 'communication', source: 'generated', action: 'front-facing explanation gesture with one hand raised and the other relaxed' },
  { id: 'ask-front', zhName: '正面提问', direction: 'front', category: 'communication', source: 'generated', action: 'front-facing questioning pose with one palm raised and a curious expression' },
  { id: 'listen-front', zhName: '正面倾听', direction: 'front', category: 'communication', source: 'generated', action: 'front-facing attentive listening pose with hands relaxed' },
  { id: 'read-front', zhName: '正面阅读', direction: 'front', category: 'knowledge', source: 'generated', action: 'front-facing reading gesture looking down at an imaginary document, holding no object' },
  { id: 'write-front', zhName: '正面记录', direction: 'front', category: 'knowledge', source: 'generated', action: 'front-facing note-taking gesture over an imaginary surface, holding no object' },
  { id: 'review-front', zhName: '正面复核', direction: 'front', category: 'evaluation', source: 'generated', action: 'front-facing careful review pose, one hand near the chin and the other marking an imaginary checklist' },
  { id: 'compare-front', zhName: '正面对比', direction: 'front', category: 'evaluation', source: 'generated', action: 'front-facing comparison pose with both palms open at equal height like weighing two options' },
  { id: 'caution-front', zhName: '正面警示', direction: 'front', category: 'risk', source: 'generated', action: 'front-facing caution pose with one raised index finger and a serious expression' },
  { id: 'stop-front', zhName: '正面停止', direction: 'front', category: 'risk', source: 'generated', action: 'front-facing stop gesture with one open palm toward the viewer' },
  { id: 'disagree-front', zhName: '正面否定', direction: 'front', category: 'decision', source: 'generated', action: 'front-facing polite disagreement pose with crossed forearms forming a clear no gesture' },
  { id: 'decide-front', zhName: '正面决策', direction: 'front', category: 'decision', source: 'generated', action: 'front-facing decisive pose with one hand pointing down as if choosing an option' }
];

export const agentAssets = [
  { id: 'idle', zhName: '正面待机', direction: 'front', category: 'baseline', source: 'v1', action: 'neutral ready state' },
  { id: 'search', zhName: '搜索', direction: 'front', category: 'knowledge', source: 'v1', action: 'leaning forward and scanning for information' },
  { id: 'receive-tool', zhName: '接收工具', direction: 'front', category: 'tools', source: 'v1', action: 'open hand ready to receive a tool' },
  { id: 'execute', zhName: '正面执行', direction: 'front', category: 'execution', source: 'v1', action: 'pressing an imaginary control to execute' },
  { id: 'store-memory', zhName: '存储记忆', direction: 'front', category: 'memory', source: 'v1', action: 'moving information toward the tool-belt memory' },
  { id: 'recall-memory', zhName: '读取记忆', direction: 'front', category: 'memory', source: 'v1', action: 'retrieving information from the tool belt' },
  { id: 'success', zhName: '成功', direction: 'front', category: 'result', source: 'v1', action: 'confident thumbs-up success state' },
  { id: 'failure', zhName: '失败', direction: 'front', category: 'result', source: 'v1', action: 'slumped failure state with a sad face' },
  { id: 'point-right', zhName: '指向右侧', direction: 'right', category: 'directional', source: 'generated', action: 'pointing clearly toward content on the right' },
  { id: 'point-left', zhName: '指向左侧', direction: 'left', category: 'directional', source: 'generated', action: 'pointing clearly toward content on the left' },
  { id: 'look-right', zhName: '观察右侧', direction: 'right', category: 'directional', source: 'generated', action: 'turning the face screen and body to inspect content on the right' },
  { id: 'look-left', zhName: '观察左侧', direction: 'left', category: 'directional', source: 'generated', action: 'turning the face screen and body to inspect content on the left' },
  { id: 'present-right', zhName: '展示右侧', direction: 'right', category: 'directional', source: 'generated', action: 'open-palm presentation gesture toward content on the right' },
  { id: 'present-left', zhName: '展示左侧', direction: 'left', category: 'directional', source: 'generated', action: 'open-palm presentation gesture toward content on the left' },
  { id: 'receive-right', zhName: '从右接收', direction: 'right', category: 'directional', source: 'generated', action: 'receiving an imaginary tool or task from the right with open hands, holding no external object' },
  { id: 'receive-left', zhName: '从左接收', direction: 'left', category: 'directional', source: 'generated', action: 'receiving an imaginary tool or task from the left with open hands, holding no external object' },
  { id: 'execute-right', zhName: '执行右侧', direction: 'right', category: 'directional', source: 'generated', action: 'pressing an imaginary control positioned on the right' },
  { id: 'execute-left', zhName: '执行左侧', direction: 'left', category: 'directional', source: 'generated', action: 'pressing an imaginary control positioned on the left' },
  { id: 'handoff-right', zhName: '向右交付', direction: 'right', category: 'directional', source: 'generated', action: 'handing an imaginary completed artifact toward the right, holding no external object' },
  { id: 'handoff-left', zhName: '向左交付', direction: 'left', category: 'directional', source: 'generated', action: 'handing an imaginary completed artifact toward the left, holding no external object' },
  { id: 'move-right', zhName: '向右推进', direction: 'right', category: 'directional', source: 'generated', action: 'walking or advancing purposefully toward the right' },
  { id: 'move-left', zhName: '向左推进', direction: 'left', category: 'directional', source: 'generated', action: 'walking or advancing purposefully toward the left' },
  { id: 'monitor-right', zhName: '监控右侧', direction: 'right', category: 'directional', source: 'generated', action: 'watching an imaginary status display on the right with an attentive face screen' },
  { id: 'monitor-left', zhName: '监控左侧', direction: 'left', category: 'directional', source: 'generated', action: 'watching an imaginary status display on the left with an attentive face screen' },
  { id: 'ask-front', zhName: '正面提问', direction: 'front', category: 'communication', source: 'generated', action: 'front-facing questioning pose with one palm raised and a curious face screen' },
  { id: 'listen-front', zhName: '正面倾听', direction: 'front', category: 'communication', source: 'generated', action: 'front-facing attentive listening pose' },
  { id: 'plan-front', zhName: '正面规划', direction: 'front', category: 'reasoning', source: 'generated', action: 'front-facing planning pose arranging imaginary steps with both hands, no external objects' },
  { id: 'reason-front', zhName: '正面推理', direction: 'front', category: 'reasoning', source: 'generated', action: 'front-facing thoughtful reasoning pose with one hand near the face screen' },
  { id: 'read-front', zhName: '正面阅读', direction: 'front', category: 'knowledge', source: 'generated', action: 'front-facing reading pose looking down at an imaginary document, holding no object' },
  { id: 'write-front', zhName: '正面记录', direction: 'front', category: 'knowledge', source: 'generated', action: 'front-facing note-taking gesture over an imaginary surface, holding no object' },
  { id: 'compare-front', zhName: '正面对比', direction: 'front', category: 'evaluation', source: 'generated', action: 'front-facing comparison pose with both palms open like weighing two options' },
  { id: 'verify-front', zhName: '正面核验', direction: 'front', category: 'evaluation', source: 'generated', action: 'front-facing verification pose with one confident check gesture and focused face screen' },
  { id: 'evaluate-front', zhName: '正面评估', direction: 'front', category: 'evaluation', source: 'generated', action: 'front-facing evaluation pose inspecting an imaginary result with both hands' },
  { id: 'alert-front', zhName: '正面告警', direction: 'front', category: 'risk', source: 'generated', action: 'front-facing alert pose with raised hands and a warning expression on the face screen' },
  { id: 'blocked-front', zhName: '正面受阻', direction: 'front', category: 'risk', source: 'generated', action: 'front-facing blocked state with hands lowered and a frustrated but readable face screen' },
  { id: 'retry-front', zhName: '正面重试', direction: 'front', category: 'recovery', source: 'generated', action: 'front-facing retry pose with one hand making a circular again gesture' },
  { id: 'wait-front', zhName: '正面等待', direction: 'front', category: 'recovery', source: 'generated', action: 'front-facing patient waiting pose with hands together' },
  { id: 'collaborate-front', zhName: '正面协作', direction: 'front', category: 'coordination', source: 'generated', action: 'front-facing collaboration invitation with both open palms' },
  { id: 'delegate-front', zhName: '正面委派', direction: 'front', category: 'coordination', source: 'generated', action: 'front-facing delegation pose assigning an imaginary task outward with one hand' },
  { id: 'celebrate-front', zhName: '正面庆祝', direction: 'front', category: 'result', source: 'generated', action: 'front-facing celebration with both hands raised and a joyful face screen' }
];

const prop = (id, zhName, category, icon, accent = 'blue', source = 'svg') => ({
  id, zhName, category, icon, accent, source
});

export const propAssets = [
  prop('document', '文档', 'context', null, 'blue', 'v1'),
  prop('document-stack', '文档组', 'context', null, 'blue', 'v1'),
  prop('search', '搜索', 'context', null, 'blue', 'v1'),
  prop('browser', '浏览器', 'context', null, 'blue', 'v1'),
  prop('database', '数据库', 'context', null, 'blue', 'v1'),
  prop('memory', '记忆', 'context', null, 'blue', 'v1'),
  prop('folder', '文件夹', 'context', 'Folder'),
  prop('clipboard', '剪贴板', 'context', 'ClipboardList'),
  prop('note', '便签', 'context', 'StickyNote'),
  prop('book', '知识手册', 'context', 'BookOpen'),
  prop('image', '图片', 'context', 'Image'),
  prop('audio', '音频', 'context', 'FileAudio'),
  prop('video', '视频', 'context', 'Video'),
  prop('code-file', '代码文件', 'context', 'FileCode2'),
  prop('spreadsheet', '表格', 'context', 'Sheet'),

  prop('api-plug', 'API 接口', 'tools', null, 'blue', 'v1'),
  prop('tool', '通用工具', 'tools', null, 'red', 'v1'),
  prop('keyboard', '键盘', 'tools', 'Keyboard'),
  prop('terminal', '终端', 'tools', 'TerminalSquare'),
  prop('email', '邮件', 'tools', 'Mail'),
  prop('chat', '对话', 'tools', 'MessageSquare'),
  prop('calendar', '日历', 'tools', 'CalendarDays'),
  prop('cloud', '云服务', 'tools', 'Cloud'),
  prop('webhook', 'Webhook', 'tools', 'Webhook'),
  prop('form', '表单', 'tools', 'ListChecks'),
  prop('dashboard', '仪表盘', 'tools', 'LayoutDashboard'),
  prop('repository', '代码仓库', 'tools', 'GitBranch'),
  prop('package', '软件包', 'tools', 'Package'),
  prop('settings', '设置', 'tools', 'Settings'),
  prop('notification', '通知', 'tools', 'Bell', 'red'),

  prop('branch', '条件分支', 'workflow', null, 'blue', 'v1'),
  prop('loop', '循环', 'workflow', null, 'blue', 'v1'),
  prop('task-list', '任务清单', 'workflow', 'ListTodo'),
  prop('workflow', '工作流', 'workflow', 'Workflow'),
  prop('queue', '任务队列', 'workflow', 'ListOrdered'),
  prop('pipeline', '执行管线', 'workflow', 'Network'),
  prop('handoff', '交接', 'workflow', 'GitPullRequest'),
  prop('parallel-agents', '并行 Agent', 'workflow', 'Users'),
  prop('single-agent', '单 Agent', 'workflow', 'Bot'),
  prop('milestone', '里程碑', 'workflow', 'Flag'),
  prop('progress', '进度', 'workflow', 'Gauge'),
  prop('timer', '计时', 'workflow', 'Timer'),
  prop('dependency', '依赖', 'workflow', 'Link2'),
  prop('merge', '汇合', 'workflow', 'GitMerge'),
  prop('route', '路线', 'workflow', 'Map'),

  prop('result-card', '结果卡', 'evaluation', null, 'blue', 'v1'),
  prop('success', '成功', 'evaluation', null, 'blue', 'v1'),
  prop('error', '错误', 'evaluation', null, 'red', 'v1'),
  prop('warning', '警告', 'evaluation', null, 'red', 'v1'),
  prop('timeout', '超时', 'evaluation', null, 'red', 'v1'),
  prop('checklist', '验收清单', 'evaluation', 'ClipboardCheck'),
  prop('scorecard', '评分卡', 'evaluation', 'BarChart3'),
  prop('ruler', '衡量标准', 'evaluation', 'Scale'),
  prop('experiment', '实验', 'evaluation', 'FlaskConical'),
  prop('evidence', '证据', 'evaluation', 'FileCheck2'),
  prop('citation', '引用', 'evaluation', 'Quote'),
  prop('compare', '对比', 'evaluation', 'Columns'),
  prop('target', '目标', 'evaluation', 'Target'),
  prop('trend-up', '趋势上升', 'evaluation', 'TrendingUp'),
  prop('trend-down', '趋势下降', 'evaluation', 'TrendingDown', 'red'),

  prop('approval', '人工批准', 'risk', 'BadgeCheck'),
  prop('shield', '安全防护', 'risk', 'ShieldCheck'),
  prop('permission-key', '权限钥匙', 'risk', 'KeyRound'),
  prop('privacy', '隐私', 'risk', 'EyeOff'),
  prop('prompt-injection', '提示注入', 'risk', 'ShieldAlert', 'red'),
  prop('human-gate', '人工关卡', 'risk', 'Hand'),
  prop('stop', '停止', 'risk', 'Ban', 'red'),
  prop('uncertainty', '不确定', 'risk', 'CircleDashed', 'red'),
  prop('question', '问题', 'risk', 'HelpCircle', 'yellow'),
  prop('idea', '想法', 'reuse', 'Lightbulb', 'yellow'),
  prop('archive', '归档', 'reuse', 'Archive'),
  prop('forget', '遗忘', 'reuse', 'Trash2', 'red'),
  prop('summary', '摘要', 'reuse', 'FileText'),
  prop('skill-card', '技能卡', 'reuse', 'Blocks'),
  prop('team', '团队', 'reuse', 'Users')
];

export const counts = {
  human: humanAssets.length,
  agent: agentAssets.length,
  props: propAssets.length,
  total: humanAssets.length + agentAssets.length + propAssets.length
};
